CREATE TABLE Bookings (
    BookingID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID),
    TicketID INT NOT NULL FOREIGN KEY REFERENCES Tickets(TicketID)
);

DROP TABLE Bookings
